"""
channel automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
class Channel(BaseModel):
    id: Optional[str] = Field(default=None, alias="id")
    type: Optional[int] = Field(default=None, alias="type")
    guild_id: Optional[str] = Field(default=None, alias="guild_id")
    position: Optional[int] = Field(default=None, alias="position")
    name: Optional[str] = Field(default=None, alias="name")
    topic: Optional[str] = Field(default=None, alias="topic")
    nsfw: Optional[bool] = Field(default=None, alias="nsfw")
    last_message_id: Optional[str] = Field(default=None, alias="last_message_id")
    bitrate: Optional[int] = Field(default=None, alias="bitrate")
    user_limit: Optional[int] = Field(default=None, alias="user_limit")
    rate_limit_per_user: Optional[int] = Field(default=None, alias="rate_limit_per_user")
    icon: Optional[str] = Field(default=None, alias="icon")
    owner_id: Optional[str] = Field(default=None, alias="owner_id")
    application_id: Optional[str] = Field(default=None, alias="application_id")
    managed: Optional[bool] = Field(default=None, alias="managed")
    parent_id: Optional[str] = Field(default=None, alias="parent_id")
    last_pin_timestamp: Optional[str] = Field(default=None, alias="last_pin_timestamp")
    rtc_region: Optional[str] = Field(default=None, alias="rtc_region")
    video_quality_mode: Optional[int] = Field(default=None, alias="video_quality_mode")
    message_count: Optional[int] = Field(default=None, alias="message_count")
    member_count: Optional[int] = Field(default=None, alias="member_count")
    default_auto_archive_duration: Optional[int] = Field(default=None, alias="default_auto_archive_duration")
    permissions: Optional[str] = Field(default=None, alias="permissions")
    flags: Optional[int] = Field(default=None, alias="flags")
    total_message_sent: Optional[int] = Field(default=None, alias="total_message_sent")
    default_sort_order: Optional[int] = Field(default=None, alias="default_sort_order")
    default_forum_layout: Optional[int] = Field(default=None, alias="default_forum_layout")
    pass
