"""
ChannelTag automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen
from requests import RequestException
from typing import List
from typing import Dict
from typing import Any
from urllib.parse import parse_qs

from .channel import Channel
from .error_exception import ErrorException
from .message import Message

class ChannelTag(sdkgen.TagAbstract):
    def __init__(self, http_client: requests.Session, parser: sdkgen.Parser):
        super().__init__(http_client, parser)


    def get(self, channel_id: str) -> Channel:
        """
        Get a channel by ID. Returns a channel object.
        """
        try:
            path_params = {}
            path_params['channel_id'] = channel_id

            query_params = {}

            query_struct_names = []

            url = self.parser.url('/channels/:channel_id', path_params)

            options = {}
            options['headers'] = {}
            options['params'] = self.parser.query(query_params, query_struct_names)



            response = self.http_client.request('GET', url, **options)

            if response.status_code >= 200 and response.status_code < 300:
                data = Channel.model_validate_json(json_data=response.content)

                return data

            statusCode = response.status_code
            if statusCode == 400:
                data = Error.model_validate_json(json_data=response.content)

                raise ErrorException(data)

            if statusCode == 404:
                data = Error.model_validate_json(json_data=response.content)

                raise ErrorException(data)

            if statusCode == 500:
                data = Error.model_validate_json(json_data=response.content)

                raise ErrorException(data)

            raise sdkgen.UnknownStatusCodeException('The server returned an unknown status code: ' + str(statusCode))
        except RequestException as e:
            raise sdkgen.ClientException('An unknown error occurred: ' + str(e))

    def get_pins(self, channel_id: str) -> List[Message]:
        """
        Returns all pinned messages in the channel as an array of message objects.
        """
        try:
            path_params = {}
            path_params['channel_id'] = channel_id

            query_params = {}

            query_struct_names = []

            url = self.parser.url('/channels/:channel_id/pins', path_params)

            options = {}
            options['headers'] = {}
            options['params'] = self.parser.query(query_params, query_struct_names)



            response = self.http_client.request('GET', url, **options)

            if response.status_code >= 200 and response.status_code < 300:
                data = List[Message].model_validate_json(json_data=response.content)

                return data

            statusCode = response.status_code
            if statusCode == 400:
                data = Error.model_validate_json(json_data=response.content)

                raise ErrorException(data)

            if statusCode == 404:
                data = Error.model_validate_json(json_data=response.content)

                raise ErrorException(data)

            if statusCode == 500:
                data = Error.model_validate_json(json_data=response.content)

                raise ErrorException(data)

            raise sdkgen.UnknownStatusCodeException('The server returned an unknown status code: ' + str(statusCode))
        except RequestException as e:
            raise sdkgen.ClientException('An unknown error occurred: ' + str(e))



