"""
Client automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen
from requests import RequestException
from typing import List
from typing import Dict
from typing import Any
from urllib.parse import parse_qs

from .channel_tag import ChannelTag
from .message_tag import MessageTag
from .user_tag import UserTag

class Client(sdkgen.ClientAbstract):
    def __init__(self, base_url: str, credentials: sdkgen.CredentialsInterface):
        super().__init__(base_url, credentials)

    def channel(self) -> ChannelTag:
        return ChannelTag(
            self.http_client,
            self.parser
        )

    def message(self) -> MessageTag:
        return MessageTag(
            self.http_client,
            self.parser
        )

    def user(self) -> UserTag:
        return UserTag(
            self.http_client,
            self.parser
        )



    @staticmethod
    def build(token: str):
        return Client("https://discord.com/api/v10", sdkgen.HttpBearer(token))


    @staticmethod
    def buildAnonymous():
        return Client("https://discord.com/api/v10", sdkgen.Anonymous())
