"""
ErrorException automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import sdkgen

from .error import Error

class ErrorException(sdkgen.KnownStatusCodeException):
    payload: Error = None

    def __init__(self, payload):
        self.payload = Error.model_validate_json(json_data=payload)

    def get_payload(self) -> Error:
        return self.payload
