"""
message_allowed_mentions automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
class MessageAllowedMentions(BaseModel):
    parse: Optional[List[str]] = Field(default=None, alias="parse")
    roles: Optional[List[str]] = Field(default=None, alias="roles")
    users: Optional[List[str]] = Field(default=None, alias="users")
    replied_user: Optional[bool] = Field(default=None, alias="replied_user")
    pass
