"""
user automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
class User(BaseModel):
    id: Optional[str] = Field(default=None, alias="id")
    username: Optional[str] = Field(default=None, alias="username")
    discriminator: Optional[str] = Field(default=None, alias="discriminator")
    global_name: Optional[str] = Field(default=None, alias="global_name")
    avatar: Optional[str] = Field(default=None, alias="avatar")
    bot: Optional[bool] = Field(default=None, alias="bot")
    system: Optional[bool] = Field(default=None, alias="system")
    mfa_enabled: Optional[bool] = Field(default=None, alias="mfa_enabled")
    banner: Optional[str] = Field(default=None, alias="banner")
    accent_color: Optional[int] = Field(default=None, alias="accent_color")
    locale: Optional[str] = Field(default=None, alias="locale")
    verified: Optional[bool] = Field(default=None, alias="verified")
    email: Optional[str] = Field(default=None, alias="email")
    flags: Optional[int] = Field(default=None, alias="flags")
    premium_type: Optional[int] = Field(default=None, alias="premium_type")
    public_flags: Optional[int] = Field(default=None, alias="public_flags")
    pass
